#!/usr/bin/env bash
# 生成 demo 用的自签 CA + broker 服务端证书,并把 CA 转成 src/ca_cert.h
# 用法: ./tools/gen_certs.sh <broker_ip> [额外IP...]
#   例: ./tools/gen_certs.sh 192.168.1.42
set -euo pipefail
cd "$(dirname "$0")/.."

BROKER_IP="${1:?用法: gen_certs.sh <broker_ip> [额外IP...]}"
shift || true

SAN="IP:${BROKER_IP}"
for ip in "$@"; do
	SAN="${SAN},IP:${ip}"
done
SAN="${SAN},IP:127.0.0.1,DNS:localhost"

mkdir -p certs
openssl req -x509 -newkey rsa:2048 -keyout certs/ca.key -out certs/ca.crt \
	-days 3650 -nodes -subj "/CN=atnode-demo-ca"
openssl req -newkey rsa:2048 -keyout certs/server.key -out certs/server.csr \
	-nodes -subj "/CN=atnode-broker"
echo "subjectAltName=${SAN}" > certs/san.cnf
openssl x509 -req -in certs/server.csr -CA certs/ca.crt -CAkey certs/ca.key \
	-CAcreateserial -out certs/server.crt -days 3650 -extfile certs/san.cnf

{
	echo "/* Auto-generated by tools/gen_certs.sh — demo CA cert (DER) */"
	echo "#ifndef CA_CERT_H"
	echo "#define CA_CERT_H"
	echo "static const unsigned char ca_certificate[] = {"
	openssl x509 -in certs/ca.crt -outform DER | xxd -i
	echo "};"
	echo "#endif"
} > src/ca_cert.h

echo "OK: certs/ 与 src/ca_cert.h 已生成 (SAN: ${SAN})"
