#!/usr/bin/env python3
"""Build the AT-Node web UI into a gzipped single-page C header.

Inlines style.css and app.js into index.html, gzips the result, and emits
../esp32_at_node/web_page.h with a PROGMEM byte array. The firmware serves
the array in one response with Content-Encoding: gzip — no heap copy, no
repeated HTML requests; all dynamic content comes from JSON APIs.

Run:  uv run python esp32/web/build.py
"""
import gzip
import pathlib

SRC = pathlib.Path(__file__).parent
OUT = SRC.parent / "esp32_at_node" / "web_page.h"

html = (SRC / "index.html").read_text(encoding="utf-8")
css = (SRC / "style.css").read_text(encoding="utf-8")
js = (SRC / "app.js").read_text(encoding="utf-8")

html = html.replace('<link rel="stylesheet" href="style.css">', f"<style>{css}</style>")
html = html.replace('<script src="app.js"></script>', f"<script>{js}</script>")

raw = html.encode("utf-8")
gz = gzip.compress(raw, compresslevel=9, mtime=0)

lines = []
for i in range(0, len(gz), 16):
    lines.append("  " + ",".join(f"0x{b:02x}" for b in gz[i : i + 16]) + ",")

OUT.write_text(
    "/* Auto-generated by esp32/web/build.py — do not edit. */\n"
    "#pragma once\n"
    "#include <pgmspace.h>\n\n"
    f"/* raw {len(raw)} bytes -> gzip {len(gz)} bytes */\n"
    "static const uint8_t WEB_PAGE_GZ[] PROGMEM = {\n"
    + "\n".join(lines)
    + "\n};\n"
    "static const size_t WEB_PAGE_GZ_LEN = sizeof(WEB_PAGE_GZ);\n",
    encoding="utf-8",
)
print(f"web_page.h: raw {len(raw)} B -> gzip {len(gz)} B")
