/**
 * build.ts — Build the AT-Node web UI into a gzipped single-page C header.
 *
 * Inlines style.css and app.js into index.html, gzips the result, and emits
 * ../web_page.h with a PROGMEM byte array. The firmware serves the array in
 * one response with Content-Encoding: gzip — no heap copy, no repeated HTML
 * requests; all dynamic content comes from JSON APIs.
 *
 * Run:  bun run build   (in esp32/arduino/web/)
 */
import { gzipSync } from "node:zlib";

const SRC = import.meta.dir;
const OUT = `${SRC}/../web_page.h`;

let html = await Bun.file(`${SRC}/index.html`).text();
const css = await Bun.file(`${SRC}/style.css`).text();
const js = await Bun.file(`${SRC}/app.js`).text();

html = html.replace(
  '<link rel="stylesheet" href="style.css">',
  `<style>${css}</style>`,
);
html = html.replace(
  '<script src="app.js"></script>',
  `<script>${js}</script>`,
);

const raw = Buffer.from(html, "utf-8");
// Node zlib writes gzip MTIME=0 by default -> deterministic output.
const gz = gzipSync(raw, { level: 9 });

const lines: string[] = [];
for (let i = 0; i < gz.length; i += 16) {
  const chunk = Array.from(gz.subarray(i, i + 16));
  lines.push("  " + chunk.map((b) => "0x" + b.toString(16).padStart(2, "0")).join(",") + ",");
}

await Bun.write(
  OUT,
  "/* Auto-generated by esp32/arduino/web/build.ts (bun run build) — do not edit. */\n" +
    "#pragma once\n" +
    "#include <pgmspace.h>\n\n" +
    `/* raw ${raw.length} bytes -> gzip ${gz.length} bytes */\n` +
    "static const uint8_t WEB_PAGE_GZ[] PROGMEM = {\n" +
    lines.join("\n") +
    "\n};\n" +
    "static const size_t WEB_PAGE_GZ_LEN = sizeof(WEB_PAGE_GZ);\n",
);

console.log(`web_page.h: raw ${raw.length} B -> gzip ${gz.length} B`);
